### ISSUE TITLE
impossible to create a new network

### ISSUE THREAD

**Issue by PFC-developer** [Abstract-OS/BOOT#29]
as NetworkInfo can't be referenced 

https://github.com/Abstract-OS/BOOT/blob/fc15f7d19bf127bc060b22586d739995aa75ea29/boot-core/src/lib.rs#L2

**Comment by PFC-developer** [comment]
prolly need 'DaemonState' 
or separate out the runtime creation with the daemon_env() creation.
(ie.. I want to do a async fetch of data so I can create the daemon) which is impossible right now.

**Comment by CyberHoward** [comment]
> prolly need 'DaemonState' or separate out the runtime creation with the daemon_env() creation. (ie.. I want to do a async fetch of data so I can create the daemon) which is impossible right now.

@PFC-developer Could you elaborate on this? Maybe in a different issue.
The issue here is that I need the `TxHandler` trait to be synchronous so it (and everything on top) is usable in a testing environment and in order for that to be possible I need an accessible runtime in the Daemon to block on. 
Don't have much experience with runtimes so open to suggestions!

**Comment by PFC-developer** [comment]
sure.. can you create a function where I can pass the runtime in vs you creating it.
